# Generated by Django 4.2.7 on 2025-09-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_newspaper"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="age_limit",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="educational_qualification",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="job_images/"),
        ),
        migrations.AddField(
            model_name="job",
            name="vacancy",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
