# Generated by Django 4.2.7 on 2025-09-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_admitcard_callletter"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="short_description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
