# Generated by Django 4.2.7 on 2025-09-07 11:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
