# Generated by Django 4.2.7 on 2025-09-09 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0008_alter_job_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='deadline',
            new_name='last_date',
        ),
    ]
