# Generated by Django 4.2.7 on 2025-09-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0009_auto_20250909_1830"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="company_name",
        ),
        migrations.RemoveField(
            model_name="job",
            name="location",
        ),
        migrations.AlterField(
            model_name="job",
            name="last_date",
            field=models.DateField(verbose_name="Last Date"),
        ),
        migrations.AlterField(
            model_name="job",
            name="posted_date",
            field=models.DateField(verbose_name="Post Date"),
        ),
    ]
