# Generated by Django 4.2.7 on 2025-09-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0010_remove_job_company_name_remove_job_location_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Job",
                "verbose_name_plural": "Jobs",
            },
        ),
        migrations.RemoveField(
            model_name="job",
            name="description",
        ),
        migrations.RemoveField(
            model_name="job",
            name="educational_qualification",
        ),
        migrations.RemoveField(
            model_name="job",
            name="last_date",
        ),
        migrations.RemoveField(
            model_name="job",
            name="posted_date",
        ),
        migrations.RemoveField(
            model_name="job",
            name="vacancy",
        ),
        migrations.AddField(
            model_name="job",
            name="application_fee",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Application Fee"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="apply_online_link",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Apply Online"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="education_qualification",
            field=models.TextField(
                blank=True, null=True, verbose_name="Education Qualification"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="end_date",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Application End Date",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="exam_pattern",
            field=models.TextField(blank=True, null=True, verbose_name="Exam Pattern"),
        ),
        migrations.AddField(
            model_name="job",
            name="official_notification_link",
            field=models.URLField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Official Notification",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="organization_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Organization Name"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="post_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Post Name"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="start_date",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Application Start Date",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="telegram_link",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Telegram Channel"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="total_vacancies",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Total Vacancies"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="job",
            name="whatsapp_link",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="WhatsApp Channel"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="youtube_link",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="YouTube Channel"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="age_limit",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Age Limit"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="short_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Short Description"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Title"),
        ),
    ]
