# Generated by Django 4.2.7 on 2025-09-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0011_alter_job_options_remove_job_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="salary",
            field=models.TextField(blank=True, null=True, verbose_name="Salary"),
        ),
    ]
