# Generated by Django 4.2.7 on 2025-09-10 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0012_job_salary"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Newspaper",
        ),
    ]
