# Generated by Django 4.2.7 on 2025-09-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0013_delete_newspaper"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="job_images/"),
        ),
    ]
