# Generated by Django 4.2.7 on 2025-09-15 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0015_auto_20250912_1017"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
        migrations.AlterModelOptions(
            name="admitcard",
            options={
                "ordering": ["order"],
                "verbose_name": "Upcoming Job",
                "verbose_name_plural": "Upcoming Jobs",
            },
        ),
    ]
