# Generated by Django 4.2.7 on 2025-09-16 13:28

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0017_alter_job_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admitcard",
            name="url",
        ),
        migrations.AddField(
            model_name="admitcard",
            name="age_limit",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="admitcard",
            name="application_fee",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="admitcard",
            name="apply_online_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="admitcard",
            name="education_qualification",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="admitcard",
            name="end_date",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="admitcard",
            name="exam_pattern",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="admitcard",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to="upcoming_job_images/",
            ),
        ),
        migrations.AddField(
            model_name="admitcard",
            name="official_notification_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="admitcard",
            name="organization_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="admitcard",
            name="post_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="admitcard",
            name="salary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="admitcard",
            name="short_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="admitcard",
            name="start_date",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="admitcard",
            name="telegram_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="admitcard",
            name="total_vacancies",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="admitcard",
            name="whatsapp_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="admitcard",
            name="youtube_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
