# Generated by Django 4.2.7 on 2025-09-19 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0018_remove_admitcard_url_admitcard_age_limit_and_more"),
    ]

    operations = []
