# Generated by Django 4.2.7 on 2025-09-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="content",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="created_at",
        ),
        migrations.AddField(
            model_name="notification",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="notification",
            name="url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
