# Generated by Django 4.2.7 on 2025-09-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_remove_notification_content_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="url",
            new_name="apply_online_link",
        ),
        migrations.AddField(
            model_name="notification",
            name="age_limit",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="application_fee",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="education_qualification",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="end_date",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="exam_pattern",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="notification_images/"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="official_notification_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="organization_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="post_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="salary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="short_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="start_date",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="telegram_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="total_vacancies",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="whatsapp_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="youtube_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
