# Generated by Django 4.2.7 on 2025-09-16 13:02

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_rename_url_notification_apply_online_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to="notification_images/",
            ),
        ),
    ]
